const foods = [
  {
    id: 1,
    restaurant_id: 1,
    name: 'UNI GUNKAN SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-5-4.jpg',
  },
  {
    id: 2,
    restaurant_id: 1,
    name: 'MAGURO AVOGADO GUNKAN SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-6.jpg',
  },
  {
    id: 3,
    restaurant_id: 1,
    name: 'YASAI GUNKAN SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-20.jpg',
  },
  {
    id: 4,
    restaurant_id: 1,
    name: 'FOAGURA TEPPANYAKI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-7-16.jpg',
  },
  {
    id: 5,
    restaurant_id: 1,
    name: 'TOKUBETSU KYOTO SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-6-9.jpg',
  },
  {
    id: 6,
    restaurant_id: 1,
    name: 'MATSU SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-1-8.jpg',
  },
  {
    id: 7,
    restaurant_id: 1,
    name: 'TAKE SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-9.jpg',
  },
  {
    id: 8,
    restaurant_id: 1,
    name: 'OTORO SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-4.jpg',
  },
  {
    id: 9,
    restaurant_id: 6,
    name: 'BOTAN EBI SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-9.jpg',
  },
  {
    id: 10,
    restaurant_id: 6,
    name: 'UME SUSHI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-11.jpg',
  },
  {
    id: 11,
    restaurant_id: 6,
    name: 'KYOTO SASHIMI MORIAWASE',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-3-15.jpg',
  },
  {
    id: 12,
    restaurant_id: 6,
    name: 'SASHIMI NANATEN MORIAWASE',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-6-13.jpg',
  },
  {
    id: 13,
    restaurant_id: 6,
    name: 'SASHIMI GOTEN A',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-11.jpg',
  },
  {
    id: 14,
    restaurant_id: 6,
    name: 'SASHIMI GO TEN B',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-7-13.jpg',
  },
  {
    id: 15,
    restaurant_id: 6,
    name: 'ISEEBI SASHIMI',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-12.jpg',
  },
  {
    id: 16,
    restaurant_id: 6,
    name: 'SASHIMI ROTKUTEN MORIAWASE',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-15.jpg',
  },
];

export default foods;
