const foods = [
  {
    id: 1,
    restaurant_id: 1,
    name: 'ウニ軍艦寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-5-4.jpg',
  },
  {
    id: 2,
    restaurant_id: 1,
    name: 'まぐろアボガド軍艦寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-6.jpg',
  },
  {
    id: 3,
    restaurant_id: 1,
    name: '野菜軍艦寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-20.jpg',
  },
  {
    id: 4,
    restaurant_id: 1,
    name: 'フォアグラ鉄板焼き',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-7-16.jpg',
  },
  {
    id: 5,
    restaurant_id: 1,
    name: '特別京都 寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-6-9.jpg',
  },
  {
    id: 6,
    restaurant_id: 1,
    name: '松寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-1-8.jpg',
  },
  {
    id: 7,
    restaurant_id: 1,
    name: '竹寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-9.jpg',
  },
  {
    id: 8,
    restaurant_id: 1,
    name: '大トロ寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-4.jpg',
  },
  {
    id: 9,
    restaurant_id: 6,
    name: 'ボタン海寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-9.jpg',
  },
  {
    id: 10,
    restaurant_id: 6,
    name: '梅寿司',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-11.jpg',
  },
  {
    id: 11,
    restaurant_id: 6,
    name: '京都刺身盛り合わせ',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-3-15.jpg',
  },
  {
    id: 12,
    restaurant_id: 6,
    name: '日本刺身㍟盛り合わせ',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-6-13.jpg',
  },
  {
    id: 13,
    restaurant_id: 6,
    name: '刺身五点盛り合わせA',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-9-11.jpg',
  },
  {
    id: 14,
    restaurant_id: 6,
    name: '刺身五点盛り合わせB',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-7-13.jpg',
  },
  {
    id: 15,
    restaurant_id: 6,
    name: '伊勢海老刺身',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-12.jpg',
  },
  {
    id: 16,
    restaurant_id: 6,
    name: '刺身六点盛り合わせ',
    price: '300.000đ',
    image: 'luu-ban-nhap-tu-dong-4-15.jpg',
  },
];

export default foods;
